export const locationdata = [
    {
        key: 1,
        name: 'Unit',
        email: 'sony.realtekh@gmail.com',
        phone: "9384394234",
        address1: 'New York No. 1 Lake Park',
        address2: 'New York No. 2 Lake Park',
        country: 'India',
        city: 'Chennai',
        state: 'Tamil Nadu',
        zipcode: '600100',
        timezone: 'UTC+12:00',
        currency: 'USD',
        dateformat: 'mm/dd/yyyy',
        timeformat: '12 Hours',
        businesshour: '12 Hours',
    },
    {
        key: 2,
        name: 'Unit',
        email: 'suganya.realtekh@gmail.com',
        phone: "8765394234",
        address1: 'New York No. 1 Lake Park',
        address2: 'New York No. 2 Lake Park',
        country: 'India',
        city: 'Chennai',
        state: 'Tamil Nadu',
        zipcode: '600100',
        timezone: 'UTC+12:00',
        currency: 'USD',
        dateformat: 'mm/dd/yyyy',
        timeformat: '12 Hours',
        businesshour: '12 Hours',
    },
    {
        key: 3,
        name: 'Unit',
        email: 'aravind.realtekh@gmail.com',
        phone: "8765394234",
        address1: 'New York No. 1 Lake Park',
        address2: 'New York No. 2 Lake Park',
        country: 'India',
        city: 'Chennai',
        state: 'Tamil Nadu',
        zipcode: '600100',
        timezone: 'UTC+12:00',
        currency: 'USD',
        dateformat: 'mm/dd/yyyy',
        timeformat: '12 Hours',
        businesshour: '12 Hours',
    },
    {
        key: 4,
        name: 'Unit',
        email: 'nisha.realtekh@gmail.com',
        phone: "8765394234",
        address1: 'New York No. 1 Lake Park',
        address2: 'New York No. 2 Lake Park',
        country: 'India',
        city: 'Chennai',
        state: 'Tamil Nadu',
        zipcode: '600100',
        timezone: 'UTC+12:00',
        currency: 'USD',
        dateformat: 'mm/dd/yyyy',
        timeformat: '12 Hours',
        businesshour: '12 Hours',
    },
    {
        key: 5,
        name: 'Unit',
        email: 'naveen.realtekh@gmail.com',
        phone: "8765394234",
        address1: 'New York No. 1 Lake Park',
        address2: 'New York No. 2 Lake Park',
        country: 'India',
        city: 'Chennai',
        state: 'Tamil Nadu',
        zipcode: '600100',
        timezone: 'UTC+12:00',
        currency: 'USD',
        dateformat: 'mm/dd/yyyy',
        timeformat: '12 Hours',
        businesshour: '12 Hours',
    },
    {
        key: 6,
        name: 'Unit',
        email: 'yukesh.realtekh@gmail.com',
        phone: "8765394234",
        address1: 'New York No. 1 Lake Park',
        address2: 'New York No. 2 Lake Park',
        country: 'India',
        city: 'Chennai',
        state: 'Tamil Nadu',
        zipcode: '600100',
        timezone: 'UTC+12:00',
        currency: 'USD',
        dateformat: 'mm/dd/yyyy',
        timeformat: '12 Hours',
        businesshour: '12 Hours',
    },
    {
        key: 7,
        name: 'Unit',
        email: 'kadhir.realtekh@gmail.com',
        phone: "8765394234",
        address1: 'New York No. 1 Lake Park',
        address2: 'New York No. 2 Lake Park',
        country: 'India',
        city: 'Chennai',
        state: 'Tamil Nadu',
        zipcode: '600100',
        timezone: 'UTC+12:00',
        currency: 'USD',
        dateformat: 'mm/dd/yyyy',
        timeformat: '12 Hours',
        businesshour: '12 Hours',
    },
    {
        key: 8,
        name: 'Unit',
        email: 'valli.realtekh@gmail.com',
        phone: "8765394234",
        address1: 'New York No. 1 Lake Park',
        address2: 'New York No. 2 Lake Park',
        country: 'India',
        city: 'Chennai',
        state: 'Tamil Nadu',
        zipcode: '600100',
        timezone: 'UTC+12:00',
        currency: 'USD',
        dateformat: 'mm/dd/yyyy',
        timeformat: '12 Hours',
        businesshour: '12 Hours',
    },
    {
        key: 9,
        name: 'Unit',
        email: 'prakash.realtekh@gmail.com',
        phone: "8765394234",
        address1: 'New York No. 1 Lake Park',
        address2: 'New York No. 2 Lake Park',
        country: 'India',
        city: 'Chennai',
        state: 'Tamil Nadu',
        zipcode: '600100',
        timezone: 'UTC+12:00',
        currency: 'USD',
        dateformat: 'mm/dd/yyyy',
        timeformat: '12 Hours',
        businesshour: '12 Hours',
    },
    {
        key: 10,
        name: 'Unit',
        email: 'manoj.realtekh@gmail.com',
        phone: "8765394234",
        address1: 'New York No. 1 Lake Park',
        address2: 'New York No. 2 Lake Park',
        country: 'India',
        city: 'Chennai',
        state: 'Tamil Nadu',
        zipcode: '600100',
        timezone: 'UTC+12:00',
        currency: 'USD',
        dateformat: 'mm/dd/yyyy',
        timeformat: '12 Hours',
        businesshour: '12 Hours',
    },
];
