export const  clientdata = [
    {
        id: 1,
        clientid: 'ZINC120',
        clientOrgname: 'ABA Corp',
        federalid: "123345",
        type: "Direct Client",
        website: "abccorp.com",
        addressline1: 'New York No. 1 Lake Park',
        addressline2: 'New York No. 2 Lake Park',
        country: 'India',
        city: 'Chennai',
        state: 'Tamil Nadu',
        zipcode: '600100',
        paymentterms: 'Net 10',
        accountmanager: 'accountmanager'
    },
    {
        id: 2,
        clientid: 'ZINC121',
        clientOrgname: 'ABA Corp',
        federalid: "123345",
        type: "End client",
        website: "abccorp.com",
        addressline1: 'New York No. 1 Lake Park',
        addressline2: 'New York No. 2 Lake Park',
        country: 'India',
        city: 'Chennai',
        state: 'Tamil Nadu',
        zipcode: '600100',
        paymentterms: 'Net 10',
        accountmanager: 'accountmanager'
    },
    {
        id: 3,
        clientid: 'ZINC122',
        clientOrgname: 'ABA Corp',
        federalid: "123345",
        type: "Implementation partner",
        website: "abccorp.com",
        addressline1: 'New York No. 1 Lake Park',
        addressline2: 'New York No. 2 Lake Park',
        country: 'India',
        city: 'Chennai',
        state: 'Tamil Nadu',
        zipcode: '600100',
        paymentterms: 'Net 10',
        accountmanager: 'accountmanager'
    },
    {
        id: 4,
        clientid: 'ZINC123',
        clientOrgname: 'ABA Corp',
        federalid: "123345",
        type: "Direct Client",
        website: "abccorp.com",
        addressline1: 'New York No. 1 Lake Park',
        addressline2: 'New York No. 2 Lake Park',
        country: 'India',
        city: 'Chennai',
        state: 'Tamil Nadu',
        zipcode: '600100',
        paymentterms: 'Net 10',
        accountmanager: 'accountmanager'
    },
    {
        id: 5,
        clientid: 'ZINC124',
        clientOrgname: 'ABA Corp',
        federalid: "123345",
        type: "End client",
        website: "abccorp.com",
        addressline1: 'New York No. 1 Lake Park',
        addressline2: 'New York No. 2 Lake Park',
        country: 'India',
        city: 'Chennai',
        state: 'Tamil Nadu',
        zipcode: '600100',
        paymentterms: 'Net 10',
        accountmanager: 'accountmanager'
    },
    {
        id: 6,
        clientid: 'ZINC125',
        clientOrgname: 'ABA Corp',
        federalid: "123345",
        type: "End client",
        website: "abccorp.com",
        addressline1: 'New York No. 1 Lake Park',
        addressline2: 'New York No. 2 Lake Park',
        country: 'India',
        city: 'Chennai',
        state: 'Tamil Nadu',
        zipcode: '600100',
        paymentterms: 'Net 10',
        accountmanager: 'accountmanager'
    },
    {
        id: 7,
        clientid: 'ZINC126',
        clientOrgname: 'ABA Corp',
        federalid: "123345",
        type: "End client",
        website: "abccorp.com",
        addressline1: 'New York No. 1 Lake Park',
        addressline2: 'New York No. 2 Lake Park',
        country: 'India',
        city: 'Chennai',
        state: 'Tamil Nadu',
        zipcode: '600100',
        paymentterms: 'Net 10',
        accountmanager: 'accountmanager'
    },
    {
        id: 8,
        clientid: 'ZINC127',
        clientOrgname: 'ABA Corp',
        federalid: "123345",
        website: "abccorp.com",
        addressline1: 'New York No. 1 Lake Park',
        addressline2: 'New York No. 2 Lake Park',
        country: 'India',
        city: 'Chennai',
        state: 'Tamil Nadu',
        zipcode: '600100',
        paymentterms: 'Net 10',
        accountmanager: 'accountmanager'
    },
    {
        id: 9,
        clientid: 'ZINC128',
        clientOrgname: 'ABA Corp',
        federalid: "123345",
        type: "Implementation partner",
        website: "abccorp.com",
        addressline1: 'New York No. 1 Lake Park',
        addressline2: 'New York No. 2 Lake Park',
        country: 'India',
        city: 'Chennai',
        state: 'Tamil Nadu',
        zipcode: '600100',
        paymentterms: 'Net 10',
        accountmanager: 'accountmanager'
    },
    {
        id: 10,
        clientid: 'ZINC129',
        clientOrgname: 'ABA Corp',
        federalid: "123345",
        type: "Direct Client",
        website: "abccorp.com",
        addressline1: 'New York No. 1 Lake Park',
        addressline2: 'New York No. 2 Lake Park',
        country: 'India',
        city: 'Chennai',
        state: 'Tamil Nadu',
        zipcode: '600100',
        paymentterms: 'Net 10',
        accountmanager: 'accountmanager'
    },
];
