# name: Auto Merge Dev to Main

# on:
#   push:
#     branches:
#       - dev

# permissions:
#   contents: write
#   pull-requests: write
#   actions: write  # Required for modifying workflows

# jobs:
#   merge:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0  # Fetch full history for merging

#       - name: Configure Git
#         run: |
#           git config --global user.name "github-actions"
#           git config --global user.email "actions@github.com"

#       - name: Checkout main branch
#         run: |
#           git checkout main
#           git pull origin main  # Ensure the latest version

#       - name: Merge dev into main (resolve conflicts in favor of dev)
#         run: |
#           git merge dev --strategy-option=theirs || true
#           git commit -am "Auto-merging dev into main - resolved conflicts with dev's changes" || true

#       - name: Push merged changes
#         run: git push origin main
#         env:
#           GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use a PAT token

name: Auto Merge Dev to Main

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history for merging

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Checkout main branch
        run: |
          git checkout main
          git pull origin main  # Ensure latest version

      - name: Merge dev into main (force merge)
        run: |
          git merge dev --no-edit --strategy-option=theirs || true
          git push origin main  # Force push to main
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use PAT for pushing
