name: Auto Merge Dev to Main

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Fetch latest changes
        run: |
          git fetch --all

      - name: Merge dev into main
        run: |
          git checkout main
          git pull origin main
          git merge --no-ff dev -m "Auto-merging dev into main" || true

      - name: Resolve conflicts (if any)
        run: |
          git diff --name-only --diff-filter=U | while read file; do
            echo "Resolving conflict in $file..."
            git checkout --theirs "$file"
            git add "$file"
          done
          git commit -m "Resolved merge conflicts" || echo "No conflicts to resolve"

      - name: Push changes
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use a Personal Access Token (PAT)
