name: Auto Merge Dev to Main

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write
  actions: write
  workflows: write  # ✅ Allows modifying workflow files

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history for proper merging

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Checkout main branch
        run: git checkout main

      - name: Merge dev into main (Resolve conflicts with dev’s changes)
        run: |
          git merge dev --strategy-option=theirs --allow-unrelated-histories
          git commit -am "Auto-merging dev into main - resolved conflicts with dev's changes" || echo "No changes to commit"

      - name: Push changes using PAT_TOKEN
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}



