name: Auto Merge Dev to Main

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write
  actions: write  # ✅ Allows modifying workflow files

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history for merging

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Checkout main branch
        run: git checkout main

      - name: Merge dev into main (resolve conflicts in favor of dev)
        run: |
          git merge dev --strategy-option theirs || true
          git commit -am "Auto-merging dev into main - resolved conflicts with dev's changes" || true

      - name: Push changes using PERSION_G_TOKEN
        run: |
          git push origin main || git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.PERSION_G_TOKEN }}
