# name: Trigger Jenkins on Main Push

# on:
#   push:
#     branches:
#       - main

# jobs:
#   trigger-jenkins:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Trigger Jenkins Job
#         run: |
#           curl -X POST "http://192.168.1.65:8080/job/github_actions/buildWithParameters" \
#                --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}"

name: Trigger Jenkins on Main Push

on:
  push:
    branches:
      - main

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger Jenkins Job
        run: |
          curl -X POST "http://192.168.1.65:8080/job/github_actions/buildWithParameters" \
               --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}"
